language: generic

sudo: false
dist: trusty

matrix:
  include:
    - os: linux
      env: CXX="g++-7" CC="gcc-7"
      compiler: gcc
      addons:
        apt:
          packages:
            - g++-7
            - cmake
            - clang-format-5.0
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
    - os: linux
      env: CXX="g++-6" CC="gcc-6"
      compiler: gcc
      addons:
        apt:
          packages:
            - g++-6
            - cmake
            - clang-format-5.0
          sources: *sources
    - os: linux
      env: CXX="clang++-4.0" CC="clang-4.0"
      compiler: clang
      addons:
        apt:
          packages:
            - clang-4.0
            - g++-5
            - cmake
            - clang-format-5.0
          sources:
            - *sources
            - llvm-toolchain-trusty-4.0
    - os: linux
      env: CXX="clang++-5.0" CC="clang-5.0"
      compiler: clang
      addons:
        apt:
          packages:
            - clang-5.0
            - g++-5
            - cmake
            - clang-format-5.0
          sources: *sources
    - os: osx
      osx_image: xcode7.3
      before_install:
        - brew update # Workaround for travis issue https://github.com/travis-ci/travis-ci/issues/9913
        - brew upgrade cmake # Installed is only 3.6.2
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9.3

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/otf2-2.1

install:
  - |
    if [ ${TRAVIS_OS_NAME} == "osx" ]; then
      brew search clang-format
      brew install clang-format
      brew info clang-format
    fi
  - OTF2_VERSION=2.1 # Update cache too when changing this!
  - OTF2_DIR=${TRAVIS_BUILD_DIR}/deps/otf2-${OTF2_VERSION}
  - |
    if [ -z "$(ls -A ${OTF2_DIR})" ]; then
      wget http://www.vi-hps.org/upload/packages/otf2/otf2-${OTF2_VERSION}.tar.gz
      tar -xf otf2-${OTF2_VERSION}.tar.gz
      (cd otf2-${OTF2_VERSION} && ./configure --prefix=${OTF2_DIR} && make -j2 install)
    fi
  - export CMAKE_PREFIX_PATH=${OTF2_DIR}:${CMAKE_PREFIX_PATH}

script:
  - cmake --version
  - mkdir build && cd build
  - cmake ..
  - make -j2
  - ctest -V .
