name: Build and Test

on: [push, pull_request]

jobs:
  build-ubuntu-1604:

    runs-on: ubuntu-16.04

    strategy:
      matrix:
        compiler: [g++-5, g++-7, clang++-5.0]

    steps:
    - uses: actions/checkout@v2
    - name: Run CMake configure
      env:
        CXX: ${{ matrix.compiler }}
      run: cmake .
    - name: Build
      run: make
    - name: Run CTest
      run: ctest .
  
  build-ubuntu:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        compiler: [g++-8, g++-9, g++-10, clang++-8, clang++-9, clang++-10]

    steps:
    - uses: actions/checkout@v2
    - name: Run CMake configure
      env:
        CXX: ${{ matrix.compiler }}
      run: cmake .
    - name: Build
      run: make
    - name: Run CTest
      run: ctest .

  build-macos:

    runs-on: macos-latest

    strategy:
      matrix:
        xcode: [10.3, 11.7, default]

    steps:
    - uses: actions/checkout@v2
    - name: Select XCode
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      if: matrix.xcode != 'default'
    - name: Run CMake configure
      run: cmake .
    - name: Build
      run: make
    - name: Run CTest
      run: ctest .
